project:
  type: website
  output-dir: docs

website:
  title: "Joel Ardiaca"
  page-footer: | 
    *Built with [Quarto](https://quarto.org)*
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Notes
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



